.drone.yml
.gitignore
Makefile

Build files

---

tests/manual-test-cases/Group1-VCH-Creation-Wizard/1-01-Basic-VCH-Create.md
tests/manual-test-cases/Group1-VCH-Creation-Wizard/1-01-Basic-VCH-Create.robot
tests/resources/Util.robot
tests/resources/VCH-Creation-Wizard-UI-Util.robot
tests/resources/Vsphere-UI-Util.robot
tests/resources/Vsphere-VCH-Plugin.robot

fixes https://github.com/vmware/vic/issues/6453

Initial VCH Creation Wizard Test

---

scripts/sync-vic-ui-version.sh
tests/manual-test-cases/Group18-VIC-UI/kickoff-tests.robot

Sync version information from vic-ui with vic

---

tests/manual-test-cases/Group18-VIC-UI/18-1-VIC-UI-Installer.robot
tests/manual-test-cases/Group18-VIC-UI/18-2-VIC-UI-Uninstaller.robot
tests/manual-test-cases/Group18-VIC-UI/18-3-VIC-UI-Upgrader.robot

Fix broken script tests on remote hosts

---

scripts/sync-vic-ui-version.sh
tests/manual-test-cases/Group18-VIC-UI/kickoff-tests.robot

Fix always passing nightly tests on Jenkins

---

h5c/vic-service/src/main/java/com/vmware/vic/PropFetcher.java
h5c/vic-service/src/main/java/com/vmware/vic/mvc/ServicesController.java
h5c/vic-service/src/main/java/com/vmware/vic/services/VicUserSessionService.java
h5c/vic-service/src/main/java/com/vmware/vic/services/VicUserSessionServiceImpl.java
h5c/vic-service/src/main/resources/META-INF/spring/bundle-context-osgi.xml
h5c/vic-service/src/main/resources/META-INF/spring/bundle-context.xml
h5c/vic/src/main/webapp/WEB-INF/spring/bundle-context.xml
h5c/vic/src/vic-webapp/src/app/services/extended-usersession.service.spec.ts
h5c/vic/src/vic-webapp/src/app/services/extended-usersession.service.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.spec.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts

Fix broken vSphere admin detection for H5 Client on 6.5u1

---

Makefile
h5c/vic-service/src/main/java/com/vmware/vic/PropFetcher.java
h5c/vic-service/src/main/java/com/vmware/vic/model/constants/BaseVm.java
h5c/vic-service/src/main/java/com/vmware/vic/mvc/ServicesController.java
h5c/vic-service/src/main/java/com/vmware/vic/services/VicApplianceService.java
h5c/vic-service/src/main/java/com/vmware/vic/services/VicApplianceServiceImpl.java
h5c/vic-service/src/main/resources/META-INF/spring/bundle-context-osgi.xml
h5c/vic-service/src/main/resources/META-INF/spring/bundle-context.xml
h5c/vic/src/main/webapp/WEB-INF/spring/bundle-context.xml
h5c/vic/src/vic-webapp/package.json
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/general/general.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/general/general.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/general/general.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/summary/summary.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/summary/summary.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/summary/summary.html
h5c/vic/src/vic-webapp/src/app/shared/constants/create-vch-wizard.ts
tests/manual-test-cases/Group18-VIC-UI/kickoff-tests.robot

This PR is a WIP implementation for looking up VIC appliance VMs inside the vic-service Java project (#26). It exposes an endpoint `/ui/vic/rest/services/get-vic-appliances` that will return information on available OVA appliance VMs from the vSphere inventory such as VM name, OVA version and build number and IP address of the VM. In order for the feature to actually work, corresponding work from the backend should be implemented as well.

Implement endpoint for vic appliances list

---

h5c/vic-service/src/main/java/com/vmware/vic/PropFetcher.java
h5c/vic-service/src/main/java/com/vmware/vic/mvc/ServicesController.java
h5c/vic-service/src/main/java/com/vmware/vic/services/CloneTicketService.java
h5c/vic-service/src/main/java/com/vmware/vic/services/CloneTicketServiceImpl.java
h5c/vic-service/src/main/resources/META-INF/spring/bundle-context-osgi.xml
h5c/vic-service/src/main/resources/META-INF/spring/bundle-context.xml
h5c/vic/src/main/webapp/WEB-INF/spring/bundle-context.xml
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts
h5c/vic/src/vic-webapp/src/app/shared/constants/create-vch-wizard.ts
h5c/vic/src/vic-webapp/yarn.lock

Fixes https://github.com/vmware/vic/issues/6596

Acquiring clone ticket from vsphere

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts
h5c/vic/src/vic-webapp/src/app/shared/vSphereClientSdkTypes.ts

Updating create vch request url to use clone ticket and appliance/vc ip addresses

Updating create vch request url 

---

Makefile
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.html

[WIP] Fix the broken plugin-manifest file

---

scripts/VCSA/install.sh
scripts/VCSA/uninstall.sh
scripts/VCSA/upgrade.sh
scripts/vCenterForWindows/install.bat
scripts/vCenterForWindows/uninstall.bat
scripts/vCenterForWindows/upgrade.bat

Update batch scripts to handle trusted certs properly

---

tests/manual-test-cases/Group18-VIC-UI/18-1-VIC-UI-Installer.robot
tests/manual-test-cases/Group18-VIC-UI/18-2-VIC-UI-Uninstaller.robot
tests/manual-test-cases/Group18-VIC-UI/18-3-VIC-UI-Upgrader.robot
tests/manual-test-cases/Group18-VIC-UI/VicUiInstallPexpectLibrary.py
tests/manual-test-cases/Group18-VIC-UI/kickoff-tests.robot

Previous merge didn't include updates to the script test cases which made the nightly tests fail. This PR fixes #40 https://github.com/vmware/vic-ui/issues/40#issuecomment-343021408

Update script test cases

---

h5c/vic/src/vic-webapp/src/app/vch-view/vch-log-view/vch-log-view.component.spec.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-log-view/vch-log-view.component.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-log-view/vch-log-view.scss
h5c/vic/src/vic-webapp/src/app/vch-view/vch-log-view/vch-log-view.template.html
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.template.html

Fix VCH log parsing

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts

Fix the container pre/postfix issue

---

h5c/vic-service/src/main/java/com/vmware/vic/mvc/DataAccessController.java

Fix incorrect totalResultCount when filter is used

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/general/general.html

Fix debug drop-down signpost typo

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/general/general.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/summary/summary.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/summary/summary.component.ts

This PR removes CLI output options with 0 and empty values in the Create VCH wizard

Fix cli options output

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/security/security.component.ts

Fix security step fields and form validity on disabling secure access

---

h5c/vic/src/main/locale/de_DE/com_vmware_vic.properties
h5c/vic/src/main/locale/en_US/com_vmware_vic.properties
h5c/vic/src/main/locale/fr_FR/com_vmware_vic.properties
h5c/vic/src/main/locale/ja_JP/com_vmware_vic.properties
h5c/vic/src/main/locale/ko_KR/com_vmware_vic.properties
h5c/vic/src/main/locale/zh_CN/com_vmware_vic.properties
h5c/vic/src/main/locale/zh_TW/com_vmware_vic.properties
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts
h5c/vic/src/vic-webapp/src/app/delete-vch-modal/delete-vch-modal.component.ts
h5c/vic/src/vic-webapp/src/app/shared/constants/create-vch-wizard.ts
h5c/vic/src/vic-webapp/src/app/shared/constants/resources.path.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.scss
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.template.html

Fixes #91 and #93 
Also adds better text handling for VCHs that are newly created

Fix VCH view refresh bug and implement refresh for VCH delete

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.scss

Showing error messages on summary page and showing spinner on create

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/general/general.html

changed postfix to suffix

---

h5c/vic/src/vic-webapp/src/app/summary-view/summary-view.component.html
h5c/vic/src/vic-webapp/src/app/summary-view/summary-view.component.ts
h5c/vic/src/vic-webapp/src/app/summary-view/vic-summary-view.scss

Add introductory text to VIC summary page

---

LICENSE.txt
NOTICE.txt

updating to 1.3 license

---

h5c/vic-service/src/main/java/com/vmware/vic/PropFetcher.java
h5c/vic-service/src/main/java/com/vmware/vic/model/VicApplianceVm.java
h5c/vic-service/src/main/java/com/vmware/vic/model/constants/BaseVm.java

Update VIC UI service to use managedBy for OVA lookup

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/general/general.html

Add Container VM name convention signpost and update Debug signpost

---

h5c/vic/src/vic-webapp/src/app/container-view/container-view.component.spec.ts
h5c/vic/src/vic-webapp/src/app/container-view/container-view.component.ts
h5c/vic/src/vic-webapp/src/app/container-view/container-view.module.ts
h5c/vic/src/vic-webapp/src/app/container-view/container-view.template.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/general/general.html
h5c/vic/src/vic-webapp/src/app/summary-view/summary-view.component.html
h5c/vic/src/vic-webapp/src/app/summary-view/summary-view.component.spec.ts
h5c/vic/src/vic-webapp/src/app/summary-view/summary-view.component.ts
h5c/vic/src/vic-webapp/src/app/summary-view/summary-view.module.ts
h5c/vic/src/vic-webapp/src/app/summary-view/vic-summary-view.scss
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.spec.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.template.html

Add warning and action buttons for verifying and accepting SSL certs

---

h5c/vic/src/vic-webapp/e2e/app.e2e-spec.ts
h5c/vic/src/vic-webapp/e2e/app.po.ts
h5c/vic/src/vic-webapp/protractor.conf.js
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/operations-user/operations-user.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/security/security.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/storage-capacity/storage-capacity.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/summary/summary.html
h5c/vic/src/vic-webapp/src/app/services/vm-view.service.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.template.html

e2e tests for create and delete vch

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/operations-user/operations-user.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/operations-user/operations-user.html

Add 'grant permissions' option to Operations User step

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts

Fix broken VCH create wizard on 6.5u1

---

h5c/vic/src/vic-webapp/e2e/app.e2e-spec.ts
h5c/vic/src/vic-webapp/e2e/app.po.ts

Found failure on e2e vch create/delete tests on fast connection (fails to find an element after vch create is completed too quickly and modal is closed). To fix this, added extra safeguard element checking and consolidated functionality into util functions.

Update integration tests to prevent elements not found failures

---

scripts/sync-vic-ui-version.sh

Updated plugin-manifest summary

---

h5c/vic/src/vic-webapp/src/app/delete-vch-modal/delete-vch-modal.component.ts
h5c/vic/src/vic-webapp/src/app/shared/constants/delete-vch-modal.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.template.html

Also, this PR fixes delete VCH button style
Fixes #128

Fix delete VCH error event handling

---

h5c/vic/src/vic-webapp/src/app/services/extended-usersession.service.spec.ts
h5c/vic/src/vic-webapp/src/app/services/extended-usersession.service.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.spec.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.template.html

Removed check for isVsphereAdmin

---

h5c/vic/src/vic-webapp/src/app/delete-vch-modal/delete-vch-modal.component.ts
h5c/vic/src/vic-webapp/src/app/shared/constants/delete-vch-modal.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.template.html

* Fix delete VCH error event handling
Also, fix delete VCH button style
* Fix integration tests
Fixes #137

Cherry-pick: Fix delete VCH error event handling (#137)

---

h5c/vic/src/vic-webapp/src/app/services/extended-usersession.service.spec.ts
h5c/vic/src/vic-webapp/src/app/services/extended-usersession.service.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.spec.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.template.html

Cherry-pick: remove admin check

---

h5c/vic/src/vic-webapp/src/app/delete-vch-modal/delete-vch-modal.component.html

Fix Delete VCH modal textual related issues

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/summary/summary.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/summary/summary.html

- Reorganize Network fields
- Add firewall policy field to container networks
Fixes #70 
Fixes #123

Update Network step layout and fields

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.html

Update VCH endpoint section title for Create wizard

---

h5c/vic/src/vic-webapp/src/app/delete-vch-modal/delete-vch-modal.component.html

Cherry-pick: delete vch modal text fixes

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/summary/summary.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/summary/summary.html

Fixes #123 
Fixes #70 
Layout, Labels, validation, network documention url fixed.

Cherry-pick: network section fixes

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.html

Add documentation links for Create wizard steps

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/security/security.html

Fix Common Name (CN) Signpost position value

---

h5c/vic-service/src/main/java/com/vmware/vic/PropFetcher.java
h5c/vic/src/vic-webapp/src/app/app.component.spec.ts
h5c/vic/src/vic-webapp/src/app/container-view/container-view.component.spec.ts
h5c/vic/src/vic-webapp/src/app/container-view/container-view.module.ts
h5c/vic/src/vic-webapp/src/app/container-view/container-view.template.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts
h5c/vic/src/vic-webapp/src/app/shared/shared.module.ts
h5c/vic/src/vic-webapp/src/app/shared/vic-ova-verification.component.ts
h5c/vic/src/vic-webapp/src/app/summary-view/summary-view.component.html
h5c/vic/src/vic-webapp/src/app/summary-view/summary-view.component.spec.ts
h5c/vic/src/vic-webapp/src/app/summary-view/summary-view.module.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.spec.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.module.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.template.html

Handle other HTTP response codes while checking vic-machine-server endpoint

---

h5c/vic-service/src/main/java/com/vmware/vic/PropFetcher.java
h5c/vic/src/vic-webapp/src/app/app.component.spec.ts
h5c/vic/src/vic-webapp/src/app/container-view/container-view.component.spec.ts
h5c/vic/src/vic-webapp/src/app/container-view/container-view.module.ts
h5c/vic/src/vic-webapp/src/app/container-view/container-view.template.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts
h5c/vic/src/vic-webapp/src/app/shared/shared.module.ts
h5c/vic/src/vic-webapp/src/app/shared/vic-ova-verification.component.ts
h5c/vic/src/vic-webapp/src/app/summary-view/summary-view.component.html
h5c/vic/src/vic-webapp/src/app/summary-view/summary-view.component.spec.ts
h5c/vic/src/vic-webapp/src/app/summary-view/summary-view.module.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.spec.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.module.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.template.html

Cherry-pick: Handle other HTTP response codes while checking vic-machine-server endpoint (#113)

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.html

Cherry-pick: documentation links

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/security/security.html

Cherry-pick: signpost position

---

h5c/vic/src/vic-webapp/e2e/app.e2e-spec.ts
h5c/vic/src/vic-webapp/e2e/app.po.ts
tests/manual-test-cases/Group1-VCH-Creation-Wizard/1-01-Basic-VCH-Create.robot
tests/manual-test-cases/Group18-VIC-UI/kickoff-tests.robot
tests/manual-test-cases/Group18-VIC-UI/vicui-common.robot

Make VCH create/delete tests more stable

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/general/general.html

Fix wizard Syslog Signpost text content

---

h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.template.html

Add an 'unknown-status' icon for VCH list

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/general/general.html

Cherry-pick: signpost text

---

h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.template.html

Cherry-pick: status icon

---

h5c/vic/src/vic-webapp/e2e/app.po.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.template.html

Download vch cert

---

h5c/vic/src/vic-webapp/e2e/app.po.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-resource-treenode.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-resource-treenode.template.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.module.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/general/general.component.ts
h5c/vic/src/vic-webapp/src/app/shared/constants/nodetype.ts

Fix compute resource selector bug

---

h5c/vic-service/src/main/java/com/vmware/vic/PropFetcher.java

Use continueRetrievePropertiesEx()

---

h5c/vic-service/src/main/java/com/vmware/vic/PropFetcher.java

Cherry-pick: vch retrieval

---

h5c/vic/src/vic-webapp/package.json
h5c/vic/src/vic-webapp/yarn.lock

Upgrade for zone.js

---

h5c/vic/src/vic-webapp/src/app/app.module.ts
h5c/vic/src/vic-webapp/src/app/shared/utils/disable-cookie-xsrf-strategy.ts

Fix XSRF-TOKEN issue

---

h5c/vic/src/vic-webapp/src/app/app.module.ts
h5c/vic/src/vic-webapp/src/app/shared/utils/disable-cookie-xsrf-strategy.ts

Cherry-pick: Fix XSRF-TOKEN issue (#198)

---

h5c/vic/src/vic-webapp/package.json
h5c/vic/src/vic-webapp/yarn.lock

Cherry-pick: Required upgrade for zone.js (#197)

---

h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts

Parsing MessageEvent body to get error message

---

h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts

Cherry-pick: Parsing MessageEvent body to get error message (#203)

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-resource-treenode.component.ts

Fix indefinitely loading tree node widget

---

h5c/vic/src/vic-webapp/src/app/container-view/container-view.component.ts
h5c/vic/src/vic-webapp/src/app/container-view/container-view.template.html
h5c/vic/src/vic-webapp/src/app/services/vm-view.service.ts

Adding containerCount for container vm datagrid pagination

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts

Fix creation bug with static IP

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts

Fix creation bug with container network firewall

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts

Cherry-pick: fix creation bug with container network firewall (#219)

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-resource-treenode.component.ts

Cherry-pick: fix datacenter tree loading (#223)

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts

Cherry-pick: fix for static ip (#220)

---

h5c/vic/src/vic-webapp/src/app/container-view/container-view.component.ts
h5c/vic/src/vic-webapp/src/app/container-view/container-view.template.html
h5c/vic/src/vic-webapp/src/app/services/vm-view.service.ts

Cherry-pick: fix container vm pagination (#215)

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/summary/summary.component.ts

Fix management network CLI options in Create wizard

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/security/security.component.ts

Send create request to datacenter specific endpoint (#208)

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-log-view/vch-log-view.component.spec.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-log-view/vch-log-view.component.ts

Also, fix error handling for log requests since errors come in text form
Fixes #209, related to #208

Update log request to always use datacenter in request path (#209)

---

h5c/vic/src/vic-webapp/e2e/app.e2e-spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/security/security.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/security/security.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/security/security.html

Update client certificates validations in Create wizard

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/summary/summary.component.ts

Cherry-pick: cli management network (#233)

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/security/security.component.ts

Cherry-pick: datacenter specific endpoint for create (#208)

---

h5c/vic/src/vic-webapp/e2e/app.e2e-spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/security/security.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/security/security.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/security/security.html

Cherry-pick: client certificate validation (#240)

---

tests/manual-test-cases/Group18-VIC-UI/18-1-VIC-UI-Installer.robot
tests/manual-test-cases/Group18-VIC-UI/18-2-VIC-UI-Uninstaller.robot
tests/manual-test-cases/Group18-VIC-UI/18-3-VIC-UI-Upgrader.robot
tests/manual-test-cases/Group18-VIC-UI/setup-testbed.robot
tests/manual-test-cases/Group18-VIC-UI/vicui-common.robot
tests/resources/Nimbus-Util.robot

Fix SSH connection glitches-related crashes in Install, uninstall steps of e2e tests.

SSH connection retry support

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/storage-capacity/storage-capacity.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/storage-capacity/storage-capacity.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/summary/summary.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/summary/summary.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/summary/summary.html

Fix volume store CLI option name in Create wizard (#251)

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-resource-treenode.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-resource-treenode.template.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts

Fix compute resource selector bug with multi DCs

---

tests/manual-test-cases/Group1-VCH-Creation-Wizard/1-01-Basic-VCH-Create.robot
tests/manual-test-cases/Group18-VIC-UI/kickoff-tests.robot
tests/manual-test-cases/Group18-VIC-UI/vicui-common.robot

This PR fixes the broken UI test infrastructure by replacing expired testbed VMs with new ones created on Nimbus. Eventually these cloud VMs would be replaced by on-prem VMs once we have another Dell server up and ready.

Fix broken UI test infra

---

h5c/vic/src/vic-webapp/src/app/delete-vch-modal/delete-vch-modal.component.ts

Update Delete request path to include VCH datacenter

---

h5c/vic/src/vic-webapp/src/app/delete-vch-modal/delete-vch-modal.component.ts

Cherry: delete-multi-dc (#271)

---

h5c/vic/src/vic-webapp/e2e/app.po.ts

Added timeout to wait for delete modal to finish positioning

---

scripts/sync-vic-ui-version.sh

Include engine version in plugin description

---

h5c/vic/src/vic-webapp/e2e/app.po.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-resource-treenode.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-resource-treenode.template.html
tests/manual-test-cases/Group1-VCH-Creation-Wizard/1-01-Basic-VCH-Create.robot
tests/resources/Vsphere-UI-Util.robot

Fix compute resource selector widget issue

---

tests/manual-test-cases/Group18-VIC-UI/18-4-VIC-UI-Plugin-tests.md
tests/manual-test-cases/Group18-VIC-UI/18-4-VIC-UI-Plugin-tests.robot
tests/manual-test-cases/Group18-VIC-UI/kickoff-tests.robot

Skip Flex plugin automation tests

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.html
h5c/vic/src/vic-webapp/src/app/shared/utils/validators.ts

Fix CIDR regex and update networks CIDR fields validation messages

---

h5c/vic/src/vic-webapp/e2e/app.po.ts
h5c/vic/src/vic-webapp/e2e/vch-create-wizard/1-basic.e2e-spec.ts
h5c/vic/src/vic-webapp/package.json
h5c/vic/src/vic-webapp/protractor.conf.js
tests/manual-test-cases/Group1-VCH-Creation-Wizard/1-01-Basic-VCH-Create.robot
tests/manual-test-cases/Group18-VIC-UI/18-1-VIC-UI-Installer.robot
tests/manual-test-cases/Group18-VIC-UI/18-2-VIC-UI-Uninstaller.robot
tests/manual-test-cases/Group18-VIC-UI/18-3-VIC-UI-Upgrader.robot
tests/manual-test-cases/Group18-VIC-UI/kickoff-tests.robot
tests/manual-test-cases/Group18-VIC-UI/setup-testbed.robot
tests/manual-test-cases/Group18-VIC-UI/vicui-common.robot
tests/resources/Parse-Vsphere-UI-E2E-Results.robot
tests/resources/Vsphere-UI-Util.robot

Cover multi DC environment test case for VCH wizard

---

h5c/vic/src/vic-webapp/e2e/app.po.ts
h5c/vic/src/vic-webapp/e2e/vch-create-wizard/1-basic.e2e-spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-resource-treenode.template.html
tests/manual-test-cases/Group18-VIC-UI/kickoff-tests.robot

Disallow selecting ClusterHostSystem in compute resource selector widget

---

h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts

Fixes #311 (addresses the issue but will need future enhancement)

Displaying server error message for vch cert download

---

h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts

Cherry-pick: displaying server error message for vch cert download (#311)

---

tests/manual-test-cases/Group18-VIC-UI/18-1-VIC-UI-Installer.robot
tests/manual-test-cases/Group18-VIC-UI/18-2-VIC-UI-Uninstaller.robot
tests/manual-test-cases/Group18-VIC-UI/18-3-VIC-UI-Upgrader.robot
tests/manual-test-cases/Group18-VIC-UI/kickoff-tests.robot
tests/manual-test-cases/Group18-VIC-UI/setup-testbed.robot
tests/manual-test-cases/Group18-VIC-UI/vicui-common.robot
tests/resources/Vsphere-UI-Util.robot

Remove all references to VCSA 6.0 instance

---

h5c/vic/src/vic-webapp/e2e/vch-create-wizard/1-basic.e2e-spec.ts
h5c/vic/src/vic-webapp/e2e/vch-create-wizard/2-multi-dvswitch.e2e-spec.ts
h5c/vic/src/vic-webapp/src/app/testing/jasmine.constants.ts

Increase Jasmine timeout for test group 1-02

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Let me know anything that should be added here or that I may have missed or got incorrect. Thanks.
Fixes #330

Updating github issue and pr templates

---

h5c/vic/src/vic-webapp/src/app/services/vm-view.service.ts

Fix the pagination issue for Container VMs

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/operations-user/operations-user.component.ts

[X] All unit tests pass
[X] All e2e tests pass
[n/a] Unit test(s) included*
[n/a] e2e test(s) included*
[n/a] Screenshot attached and UX approved*

fixing missing pageload call

---

h5c/vic/src/vic-webapp/e2e/app.po.ts

Fixes #375 
[X] All unit tests pass
[X] All e2e tests pass
[n/a] Unit test(s) included*
[n/a] e2e test(s) included*
[n/a] Screenshot attached and UX approved*

Fix broken nightly e2e tests

---

h5c/vic/src/vic-webapp/src/app/app.module.ts
h5c/vic/src/vic-webapp/src/app/services/http-interceptor.service.spec.ts
h5c/vic/src/vic-webapp/src/app/services/http-interceptor.service.ts
h5c/vic/src/vic-webapp/src/app/shared/constants/resources.path.ts
h5c/vic/src/vic-webapp/src/app/ui-actions/ui-actions.component.ts

Fixes #228 
[X] All unit tests pass
[X] All e2e tests pass
[X] Unit test(s) included
[n/a] e2e test(s) included
[X] Screenshot attached / UX approved

http interceptor for unauthenticated session handling

---

h5c/vic/src/vic-webapp/src/app/services/http-interceptor.service.ts

Fixes issue where no observable is returned and causes type error

Return observable outside of if condition

---

tests/resources/Nimbus-Util.robot
tests/test-cases/Group5-Interoperability-Tests/5-03-Multiple-Datacenter.md
tests/test-cases/Group5-Interoperability-Tests/5-03-Multiple-Datacenter.robot

Fix for https://github.com/vmware/vic-product/issues/1360 and adding https://github.com/vmware/vic-ui/issues/399 to complete it

Nightly datacenter

---

tests/test-cases/Group5-Interoperability-Tests/5-15-NFS-Datastore.md
tests/test-cases/Group5-Interoperability-Tests/5-15-NFS-Datastore.robot

Fix for https://github.com/vmware/vic-product/issues/1363 and added #408 to complete it later

Add nightly test for nfs datastore

---

tests/test-cases/Group13-vMotion/13-01-vMotion-VCH-Appliance.md
tests/test-cases/Group13-vMotion/13-01-vMotion-VCH-Appliance.robot
tests/test-cases/Group13-vMotion/13-02-vMotion-Container.md
tests/test-cases/Group13-vMotion/13-02-vMotion-Container.robot

Fix for https://github.com/vmware/vic-product/issues/1376 and created #419 to complete it later.

Add nightly test for vmotion

---

tests/test-cases/Group5-Interoperability-Tests/5-01-Distributed-Switch.md
tests/test-cases/Group5-Interoperability-Tests/5-01-Distributed-Switch.robot

Fix for https://github.com/vmware/vic-product/issues/1359 and added #402

Add nightly test for distributed switch

---

tests/test-cases/Group5-Interoperability-Tests/5-04-Multiple-Cluster.md
tests/test-cases/Group5-Interoperability-Tests/5-04-Multiple-Cluster.robot

Fix for https://github.com/vmware/vic-product/issues/1361 and added #404 to complete the test.

Add nightly test for multiple clusters

---

tests/test-cases/Group5-Interoperability-Tests/5-12-Multiple-VLAN.md
tests/test-cases/Group5-Interoperability-Tests/5-12-Multiple-VLAN.robot

Fix for https://github.com/vmware/vic-product/issues/1362 and added #406 to complete it later.

Add nightly test for multiple vlans

---

tests/test-cases/Group5-Interoperability-Tests/5-02-Cluster.md
tests/test-cases/Group5-Interoperability-Tests/5-02-Cluster.robot

Fix for https://github.com/vmware/vic-product/issues/1368 and added #410 to complete it later.

Add nightly test for cluster

---

tests/test-cases/Group5-Interoperability-Tests/5-03-Enhanced-Linked-Mode.md
tests/test-cases/Group5-Interoperability-Tests/5-03-Enhanced-Linked-Mode.robot

Fix for https://github.com/vmware/vic-product/issues/1370 and created #412 to complete it later.

Add nightly test for enhanced link mode

---

tests/test-cases/Group5-Interoperability-Tests/5-06-1-VSAN-Simple.md
tests/test-cases/Group5-Interoperability-Tests/5-06-1-VSAN-Simple.robot

Fix for https://github.com/vmware/vic-product/issues/1371 and created #414 to complete it later.

Add nightly test for simple vsan

---

tests/test-cases/Group5-Interoperability-Tests/5-08-DRS.md
tests/test-cases/Group5-Interoperability-Tests/5-08-DRS.robot

Fix for https://github.com/vmware/vic-product/issues/1375 and created #417 to complete it.

Add nightly test for drs

---

h5c/vic/src/vic-webapp/e2e/app.po.ts
h5c/vic/src/vic-webapp/e2e/vch-create-wizard/1-basic.e2e-spec.ts
h5c/vic/src/vic-webapp/e2e/vch-create-wizard/2-multi-dvswitch.e2e-spec.ts

Fix nightly test failures for mac and win (chrome - firefox)
Fixes #421 

Fix nightly test failures (#421)

---

h5c/vic/src/vic-webapp/e2e/vch-create-wizard/1-basic.e2e-spec.ts

inexistent element by css "datagridcell"
Fixes #421 
[X ] All unit tests pass
[X ] All e2e tests pass
[ n/a] Unit test(s) included*
[ n/a] e2e test(s) included*
[ n/a] Screenshot attached and UX approved*

Fixing problems with IE 

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.html
h5c/vic/src/vic-webapp/src/app/summary-view/summary-view.component.html

* Changing docs link from 1.3 link to 1.4
* Change all the doc links from 1.3 to 1.4
Fixes #385

Cherry-pick: Changing docs link from 1.3 link to 1.4 (#437)

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-resource-treenode.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-resource-treenode.component.ts

Fix duplicated resources inside Datacenters on the VCH Creation Wizard

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-resource-treenode.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-resource-treenode.component.ts

Cherry-pick: Fix duplicated resources inside Datacenters on the VCH Creation Wizard (#445)

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts

Cherry-pick: Send DNS server setting on the api Request during VCH creation (#449)

---

LICENSE.txt
NOTICE.txt
open_source_license.txt

Cherry-pick: Updating license files from version 1.3 to 1.4 (#453)

---

h5c/vic/src/vic-webapp/src/app/container-view/container-view.component.spec.ts
h5c/vic/src/vic-webapp/src/app/container-view/container-view.template.html

Fixes #344 
[X] All unit tests pass
[X] All e2e tests pass
[X] Unit test(s) included*

Adding unit tests for VCH pagination

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.html

Set IP Range input selectable on Network during VCH Wizard creation

---

h5c/vic/src/main/locale/en_US/com_vmware_vic.properties
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.scss
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts

Fixes #401
[ x ] Screenshot attached and UX approved*
Environment existing groups:
Capture with Affinity enabled:
Capture with Affinity disabled:
Resource type validation (only enable affinity for clusters)
Cluster DRS validation:
Group name validation:
Group name and drs simultaneous validation:

Update VCH Management UI to support VM-Host Affinity

---

h5c/vic/src/vic-webapp/src/app/container-view/container-view.component.spec.ts
h5c/vic/src/vic-webapp/src/app/container-view/container-view.template.html

* -  Adding unit test casses for vch view pagination
* -  changing from ngfor to clrDgItem for display on the datagrid
-   Formating the unit test code
Fixes #344

Cherry-pick: Adding unit tests for VCH pagination (#471)

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/mocks/create-vch-wizard-mocked-data.ts
h5c/vic/src/vic-webapp/src/app/interfaces/compute.resource.ts

Cherry-pick: Fix issue with networks population when host name contains some extra text (#440)

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.html

Cherry-pick: Set IP Range input selectable on Network during VCH Wizard creation (#462)

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/registry-access/registry-access.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/registry-access/registry-access.component.ts

Fixes #380 
[x] All unit tests pass
[x] All e2e tests pass
[x ] Unit test(s) included*
[x] Screenshot attached and UX approved*

Fixed insecure registry with missing port not shown on summary

---

h5c/vic/src/vic-webapp/e2e/app.po.ts

Increase poll time trying to find an element

---

scripts/VCSA/install.sh

(cherry picked from commit 454d64e7ff3c7852e500b86c151890e7def1181a)

Cherry-pick: Fix RESPONSE STATUS value (#530)

---

tests/test-cases/Group18-VIC-UI/setup-testbed.robot

Line changed to check the activation of the CI on master branch

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts

cherry-pick from master 
Fix: datacenter can not show host in create vch wizard.

fix datacenter can not show host

---

h5c/vic/src/vic-webapp/package-lock.json
h5c/vic/src/vic-webapp/package.json
h5c/vic/src/vic-webapp/yarn.lock

Actually, this bootstrap4.0.0 is a dependency of clarity, but it is not a required for the application consume clarity.

remove bootstrap to fix security xss alert

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/security/security.component.ts

fixed the undefined error sometimes when the selectedInstance is null or undefined.

fix ca undefined console error

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/summary/summary.component.ts

fix: set compute resource name instead of id , this will cause create vch fail.

fix compute resource not set to id in api

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts

Previously, frontend only show normal portgroups  in the network select. 
We need to add opacknetwork select options in ui.

support frontend nsxt network

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts

if a data center is under a folder or nested folders, 
From the frontend should get all the datacenters until get all the folders. Otherwise, some data centers under folder can not be selected in the compute resource tree.

fix problem data center under a folder can not show up

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.html
h5c/vic/src/vic-webapp/src/app/shared/globals.service.ts
h5c/vic/src/vic-webapp/src/app/summary-view/summary-view.component.html
h5c/vic/src/vic-webapp/src/app/summary-view/summary-view.component.ts

This pr is focus on update the vic-ui document link to 1.5. 
There are many places have 1.5 document link, this is not good practise. So link version has been abstracted to a service function. there will be only one place to update in the future.

update vic ui 1.5 document link

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts

add null or undefined checking before invoke method "some"
Signed-off-by: Meina Zhou <meinaz@vmware.com>

undefine check after concat the hosts

---

h5c/vic-service/src/main/java/com/vmware/vic/PropFetcher.java
h5c/vic-service/src/main/java/com/vmware/vic/utils/ConfigLoader.java

fix stream unreleased error and null check

fix fortify issues

---

LICENSE.txt
NOTICE.txt
open_source_license.txt

Updating LICENSE, NOTCE and open_source_license files for 1.5.0 release.

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.html

change the security link url and registry link url to match the correct link.

change security and registry link url

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.html
h5c/vic/src/vic-webapp/src/app/shared/utils/validators.ts

When configuring client network or management network and assigning static ip, routing destination and gateway must exist at the same time or not at the same time.
Signed-off-by: FangyuanCheng <fangyuanc@vmware.com>

Gateway input validator for client network and management network

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/summary/summary.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/summary/summary.html
h5c/vic/src/vic-webapp/src/app/shared/utils/validators.ts

add networkwidth module
Including the modification of network-width module, network width, we can use the number between 1 and 30, in the summary page to reflect the value we filled in, you can also use the command line.

add networkwidth module

---

LICENSE.txt

some of the license package already been upgraded to the latest version. We need to upgrade packages in license file.

upgrade packages in LICENSE file

---

h5c/vic/src/vic-webapp/src/app/summary-view/summary-view.component.html

add IP address in the Summary tab a link to the appliance.
Signed-off-by: Yogi_Wang <yawang@vmware.com>
Fixes #
[Y ] All unit tests pass
[ Y] All e2e tests pass
[ N] Unit test(s) included*
[N ] e2e test(s) included*
[N ] Screenshot attached and UX approved*

addIpAdress

---

h5c/vic-service/src/main/java/com/vmware/vic/PropFetcher.java

fix issue. After upgrade, vic plugin can not find the right appliance ip address.

fix upgrade can not show correct vic appliance

---

h5c/vic-service/src/main/java/com/vmware/vic/cache/LocalCache.java

reset the timeout to 10 seconds to avoid deleting vch not refresh UI.

set the timeout period to 10 seconds

---

open_source_license.txt

Updateing open_source_license file for vic-ui 1.5.5 GA.

---

h5c/vic-service/src/main/java/com/vmware/vic/services/ResourcePoolServiceImpl.java

1. In VIC UI java layer, we import QueryUtil class which will be moved into a new package:
com.vmware.vise.data.query.QueryUtil -> com.vmware.vise.data.query.util.QueryUtil
2. we can not simply fix it by update the import path to
com.vmware.vise.data.query.util.QueryUtil
Because it will block VIC UI running on lower version before H5 client API changing.
3. Solution:
Remove the code dependency on QueryUtil class.
Add and implements three Functions to replace the original Functions
the new three funcs will provide the same function.

VIC UI is blocked on VC that including new refactoring H5 client API

---

.drone.yml
tests/check-org-membership.sh
tests/pass-rate.sh

Fixed to access github api error

---

tests/check-org-membership.sh

Hidden github token for ci output

---

.drone.yml

Update ci image due to the old image has been removed

---

h5c/vic-service/build-java.xml
h5c/vic-service/src/main/java/com/vmware/vic/filters/VicSessionFilter.java
h5c/vic-service/src/main/resources/META-INF/MANIFEST.MF
h5c/vic/src/main/webapp/META-INF/MANIFEST.MF
h5c/vic/src/main/webapp/WEB-INF/spring/bundle-context.xml
h5c/vic/src/main/webapp/WEB-INF/web.xml

1. add new jar dependency in compiling stage:
spring-core-4.3.29.RELEASE.jar

Add session filter and return 401 auth error if session was not found

---

h5c/vic/src/vic-webapp/package-lock.json
h5c/vic/src/vic-webapp/package.json

Fix security alerts

---

h5c/vic/src/vic-webapp/package-lock.json
h5c/vic/src/vic-webapp/package.json

fix security alert

---

h5c/vic/src/vic-webapp/package-lock.json
h5c/vic/src/vic-webapp/package.json

fix latest security issues
