vmware/vic-ui

tests/manual-test-cases/Group18-VIC-UI/kickoff-tests.robot

The kickoff script enforces the root folder of the project
to be 'vic', however the VIC UI has branched off it with a
new name 'vic-ui', the script always fails to start. This commit
fixes the issue.
Fixes #6

Fix broken kickoff script

---

.drone.local.plugin.yml
.drone.local.script.yml
tests/manual-test-cases/Group18-VIC-UI/18-1-VIC-UI-Installer.robot
tests/manual-test-cases/Group18-VIC-UI/18-2-VIC-UI-Uninstaller.robot
tests/manual-test-cases/Group18-VIC-UI/18-3-VIC-UI-Upgrader.robot
tests/manual-test-cases/Group18-VIC-UI/18-4-VIC-UI-Plugin-tests.robot
tests/manual-test-cases/Group18-VIC-UI/kickoff-tests.robot
tests/manual-test-cases/Group18-VIC-UI/setup-testbed.robot
tests/manual-test-cases/Group18-VIC-UI/vicui-common.robot

This PR updates the integration tests codebase such that all references to the `vic` repo are  properly replaced with `vic-ui`. Also, once merged into master, the integration tests will no longer rely on Nimbus to create testbeds. Instead, an in-house Dell server would be used in its place on which vSphere 6.0 and 6.5 instances are already deployed.
Fixes vic#6548.

Set up integration tests with the vic-ui repository

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/storage-capacity/storage-capacity.component.ts

This PR fixes a console error generated from storage-capacity when trying to obtain datastores from an undefined (not yet selected) compute resource.

Fix undefined datastore console error

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/general/general.component.spec.ts
h5c/vic/src/vic-webapp/src/app/services/extended-usersession.service.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-log-view/vch-log-view.component.spec.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-log-view/vch-log-view.component.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.module.ts

This PR updates @cristianfalcone's VCH Log component to use the VIC appliance lookup and vSphere session clone ticket endpoints such that the UI would talk to the correct API endpoint.

Make VchLogView use lookup and clone ticket endpoints

---

scripts/VCSA/configs
scripts/vCenterForWindows/configs

* Notifies user what to do in case the hostname of VIC appliance has changed
Fixes #6380 https://github.com/vmware/vic/issues/6380

Added additional messaging comments to configs

---

h5c/vic-uia/src/main/java/com/vmware/vsphere/client/automation/test/vch/VchPortletDisplaysInfoWhileOnTest.java

Since a VCH is created under a ResourcePool instead of a vApp, an E2E test case has been failing where the H5C UI no longer asks the user, in a Clarity dialog, if s/he wants to turn on the VCH VM when it's off. This PR addresses the issue.

Fix a failing test case in H5C plugin E2E tests

---

scripts/vCenterForWindows/install.bat
scripts/vCenterForWindows/uninstall.bat
scripts/vCenterForWindows/upgrade.bat

This PR addresses nightly failures on uninstaller and upgrader scripts for WIndows where trying to run the script against a non-existent host was not properly handled. It should throw an error that it could not connect to the provided host but it would go ahead and ask the user to accept the thumbprint comes out empty.

Catch when provided VC hostname/ip is incorrect

---

tests/manual-test-cases/Group18-VIC-UI/kickoff-tests.robot

This PR allows for skipping any existing test case. Skipped tests would be marked "SKIPPED" along with other tests marked either "PASSED" or "FAILED" in an email test report.

Add skip tests feature to integration tests kickoff script

---

h5c/vic/src/vic-webapp/src/app/app-routing.module.ts
h5c/vic/src/vic-webapp/src/app/delete-vch-modal/delete-vch-modal.component.html
h5c/vic/src/vic-webapp/src/app/delete-vch-modal/delete-vch-modal.component.scss
h5c/vic/src/vic-webapp/src/app/delete-vch-modal/delete-vch-modal.component.ts
h5c/vic/src/vic-webapp/src/app/delete-vch-modal/delete-vch-modal.module.ts
h5c/vic/src/vic-webapp/src/app/shared/constants/delete-vch-modal.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.spec.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.scss
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.template.html

VCH Delete 

---

tests/manual-test-cases/Group18-VIC-UI/kickoff-tests.robot
tests/manual-test-cases/Group18-VIC-UI/vicui-common.robot
tests/resources/Docker-Util.robot
tests/resources/VCH-Util.robot

UI nightly tests have been broken since last night, as the Mac Mini's IP address has been changed. Eventually we will need to switch from DHCP to a static IP but until we get one we need to ensure the IP address is timely updated should it be updated.
Also this PR adds Emmanuel Carelli to the nightly test report recipients list.

Update Mac Mini's IP to fix broken nightly tests

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/general/general.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/summary/summary.component.ts

removing password and vic-appliance-endpoint flags
escaping () and whitespace between words for CLI
Fixes #

Escaping special chars for cli command and unused removing flags

---

tests/manual-test-cases/Group18-VIC-UI/setup-testbed.robot

I realized that a change made to the `Utils.robot` requires us to set the TEST_RESOURCE env variable before deploying a test VCH for our test cases. This PR addresses this issue.

Fix up broken nightly tests

---

scripts/VCSA/install.sh

This adds some extra flags to the install script so that the H5C UI plugin can pass them to the vic-ui binary.

Supply OVA configure option in installer

---

scripts/VCSA/upgrade.sh
scripts/vCenterForWindows/install.bat
scripts/vCenterForWindows/upgrade.bat

This PR is extended work in line with #115 such that `upgrader.sh` and corresponding Windows batch scripts behave the same as `install.sh`.

Update plugin scripts to work with new vic-ui bin

---

scripts/sync-vic-ui-version.sh

..to contain both the ui build and engine build versions in the plugin-manifest
Fixes #125

Updating version sync script 

---

scripts/sync-vic-ui-version.sh

to contain both the ui build and engine build versions in the plugin-manifest (#130)
Fixes #125

Cherry-pick: Updating sync script 

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.html

Since the wizard uses the next button to perform custom validations, users navigating backwards in the wizard using the steps nav is problematic, specifically when updating Summary step and CLI command values as a result of these validations. Adding this option prevents users from jumping backwards and forwards.
Fixes #135

Add 'clrWizardForceForwardNavigation' option to Create VCH wizard

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.html

Related to #123 Somehow this single change did not get cherry-picked. We had two PRs related to networking that overrode one another. This appears to the be the only change that didn't get updated. Setting it to be same as on master.

Cherry-pick: Networking documentation link

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.html

Since the wizard uses the next button to perform custom validations, users navigating backwards in the wizard using the steps nav is problematic, specifically when updating Summary step and CLI command values as a result of these validations. Adding this option prevents users from jumping backwards and forwards.
Fixes #135

Cherry-pick: restrict wizard step navigation

---

h5c/vic/src/vic-webapp/e2e/app.po.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-resource-treenode.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-resource-treenode.template.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.module.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/general/general.component.ts
h5c/vic/src/vic-webapp/src/app/shared/constants/nodetype.ts

* Fix compute resource selector bug
* Remove redundant clr-alert comps
* Clean up
* Update protractor test to reflect changes
* Address comments
* Remove cluster from widget when no host is attached
* Safeguard getDatastores()
* Use objRef instead of alias for getting datastores
Fixes #

Cherry-pick: Fix compute resource selector bug (#172)

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.scss
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/storage-capacity/storage-capacity.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/storage-capacity/storage-capacity.scss

Update container VM image size and bridge network signposts

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.scss
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/storage-capacity/storage-capacity.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/storage-capacity/storage-capacity.scss

* Update container VM image size and bridge network signposts
* Fix image size label and bridge network signpost styles
Fixes #59 
Fixes #60

Cherry-pick: signpost text

---

tests/manual-test-cases/Group18-VIC-UI/vicui-common.robot

This PR updates test scripts such that they reflect the latest change we made to our testbed machines to use static IPs.

Use static IP for testbeds

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-log-view/vch-log-view.component.spec.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-log-view/vch-log-view.component.ts

* Update log request to always use datacenter in request path
Also, fix error handling for log requests since errors come in text form
* Fix VCH log view unit tests
Fixes #209 related to #208

Cherry-pick: datacenter specific endpoint for vch logs (#209)

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/storage-capacity/storage-capacity.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/storage-capacity/storage-capacity.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/summary/summary.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/summary/summary.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/summary/summary.html

Fix volume store CLI option name in Create wizard
Fixes #251

Cherry-pick: Fix volume store CLI option name in Create wizard (#251)

---

h5c/vic/src/vic-webapp/e2e/app.po.ts
h5c/vic/src/vic-webapp/e2e/vch-create-wizard/1-basic.e2e-spec.ts
h5c/vic/src/vic-webapp/e2e/vch-create-wizard/2-multi-dvswitch.e2e-spec.ts
h5c/vic/src/vic-webapp/e2e/vch-create-wizard/common.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.component.ts
h5c/vic/src/vic-webapp/src/app/shared/utils/array-utils.ts
tests/manual-test-cases/Group1-VCH-Creation-Wizard/1-02-Multi-DVS-VCH-Create.robot

Fixes #307 
Test steps:
1. Make sure distributed virtual switch named "DSwitch 2" is not in the VC inventory
1. govc object.destroy '/Datacenter/network/DSwitch 2
2. Create a new distributed virtual switch named "DSwitch 2"
1. govc dvs.create -dc=Datacenter 'DSwitch 2'
3. Create port groups: net1, net2
1. govc dvs.portgroup.add -nports 12 -dc=Datacenter -dvs='DSwitch 2' net1
2. govc dvs.portgroup.add -nports 12 -dc=Datacenter -dvs='DSwitch 2' net2
4. Add an idle standalone host to "DSwitch 2" (make sure to add the host to the VC beforehand!)
1. govc dvs.add -dvs='DSwitch 2' -pnic=vmnic1 -host.ip=$HOST_IP $HOST_IP
5. Open the VCH Create wizard and select "Cluster" as compute resource
6. Proceed to the "Networks" section, select port groups "bridge" and "network" for the bridge and public …

Get correct DV portgroups for the selected resource

---

.drone.local.script.yml
h5c/build-deployable.xml
h5c/vic/src/vic-webapp/e2e/app.po.ts
h5c/vic/src/vic-webapp/e2e/vch-create-wizard/1-basic.e2e-spec.ts
h5c/vic/src/vic-webapp/e2e/vch-create-wizard/2-multi-dvswitch.e2e-spec.ts
tests/resources/Nimbus-Util.robot
tests/resources/Vsphere-UI-Util.robot
tests/test-cases/Group1-VCH-Creation-Wizard/1-01-Basic-VCH-Create.robot
tests/test-cases/Group1-VCH-Creation-Wizard/1-02-Multi-DVS-VCH-Create.robot
tests/test-cases/Group18-VIC-UI/18-1-VIC-UI-Installer.robot
tests/test-cases/Group18-VIC-UI/18-2-VIC-UI-Uninstaller.robot
tests/test-cases/Group18-VIC-UI/18-3-VIC-UI-Upgrader.robot
tests/test-cases/Group18-VIC-UI/18-4-VIC-UI-Plugin-tests.md
tests/test-cases/Group18-VIC-UI/18-4-VIC-UI-Plugin-tests.robot
tests/test-cases/Group18-VIC-UI/kickoff-tests.robot
tests/test-cases/Group18-VIC-UI/setup-testbed.robot
tests/test-cases/Group18-VIC-UI/vicui-common.robot

This PR makes several changes in our nightly test scripts in such a way that the vCenter Server Appliance and ESXi VMs are no longer served on our bare metal server, but created in Nimbus on demand. Lease is set to expire in one day so we can ensure each test environment is in a clean state.
**Update**
Combined work for issue 374 because it is closely related to this PR.
Fixes #337 #374 
- [n/a] Unit test(s) included*
- [n/a] e2e test(s) included*
- [n/a] Screenshot attached and UX approved*

Switch from on-prem server to Nimbus for nightly testbed VMs

---

.drone.yml

build did not publish on tag, see here for details:
https://github.com/vmware/vic/pull/7753
refs/tags is no longer a branch

Fix drone yml events

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/mocks/create-vch-wizard-mocked-data.ts

Fixes #389 
[ x ] Screenshot attached and UX approved*

Display port groups under a network folder in the VCH creation wizard

---

.drone.yml
.travis.yml

When determining which tag to use during the build process, use the most recent tag that is reachable from the current commit instead of the most recent tag in the repository.
Include `--tags` to enable matching on lightweight tags.
Include `--abbrev=0` to suppress the long format (which includes an offset and abbreviated hash) and show only the closest tag.
Towards: vmware/vic-product#1206

Use the most recent reachable tag during build

---

LICENSE.txt
NOTICE.txt
open_source_license.txt

Updating license files from version 1.3 to 1.4

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-resource-treenode.template.html

Fix issue with empty and or duplicated nodes on resource tree selector of vch creation wizard
Fixes #441 
Screenshots attached of before and after for multivc and singlevc:
singlevc structure:
singlevc before this fix:
singlevc after this fix:
multivc structure:
multivc before this fix:
multivc after this fix:

Fix issue with empty and or duplicated nodes on resource tree selector

---

h5c/vic/src/main/webapp/plugin.xml
h5c/vic/src/vic-webapp/src/app/app-routing.module.ts
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/compute/configure-vch-view-compute.component.html
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/compute/configure-vch-view-compute.component.scss
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/compute/configure-vch-view-compute.component.ts
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/compute/configure-vch-view-compute.module.ts
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/general/configure-vch-view-general.component.html
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/general/configure-vch-view-general.component.scss
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/general/configure-vch-view-general.component.ts
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/general/configure-vch-view-general.module.ts
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/network/configure-vch-view-network.component.html
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/network/configure-vch-view-network.component.scss
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/network/configure-vch-view-network.component.ts
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/network/configure-vch-view-network.module.ts
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/operations/configure-vch-view-operations.component.html
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/operations/configure-vch-view-operations.component.scss
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/operations/configure-vch-view-operations.component.ts
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/operations/configure-vch-view-operations.module.ts
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/registry/configure-vch-view-registry.component.html
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/registry/configure-vch-view-registry.component.scss
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/registry/configure-vch-view-registry.component.ts
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/registry/configure-vch-view-registry.module.ts
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/security/configure-vch-view-security.component.html
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/security/configure-vch-view-security.component.scss
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/security/configure-vch-view-security.component.ts
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/security/configure-vch-view-security.module.ts
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/storage/configure-vch-view-storage.component.html
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/storage/configure-vch-view-storage.component.scss
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/storage/configure-vch-view-storage.component.ts
h5c/vic/src/vic-webapp/src/app/configure/configure-vch-view/storage/configure-vch-view-storage.module.ts

This change will introduce a brand new VCH Configure Menu on each VCH VM. This menu will bring individual acces to each of the VCH Configure stpes in order to allow user to view and reconfigure only a particular step related with the VCH configuration.
Fixes #391 
[ x ] Screenshot attached and UX approved*
Configure for regular VM
Configure for VCH VM

Introduce a VCH Configure Menu under the Configure view

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/mocks/create-vch-wizard-mocked-data.ts

Cherry-pick: Display port groups under a network folder in the VCH creation wizard (#436)

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-resource-treenode.template.html

Cherry-pick: Fix issue with empty and or duplicated nodes on resource tree selector of vch creation wizard (#448)

---

h5c/vic/src/main/locale/en_US/com_vmware_vic.properties
h5c/vic/src/vic-webapp/src/app/shared/constants/resources.path.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.template.html

This change will introduce a new action on the Virtual Container Hosts view datagrid. This new action will allow users to go to the reconfigure page of the desired VCH on the list.
Fixes #494 
[ x ] Screenshot attached and UX approved*

Introduce a VCH Reconfigure datagrid action on Virtual Container Hosts view

---

.drone.yml

At the completion of each vic-ui build following a push to master or a release branch, trigger a new build of vic. This will then trigger a new build of vic-product, producing an OVA with the latest UI version.
This strategy has some limitations:
* The downstream-trigger currently restarts the most recent build on
the target repository. However, this most recent build may not be
on the expected branch. (This will need to be addressed in the
downstream-trigger logic.)
* All CI OVA builds are currently published to the same directory,
making it difficult for UI automation to chose the correct OVA to
test as the intent of the automation is to test the latest build
from a specific branch. (This will need to be addressed by larger
changes to the way Drone publishes artifacts to GCS. In the …

Add downstream trigger to drone build

---

.drone.yml

Changes:
- Trigger the make process and the integration tests for the develop branch when PR created.
- Trigger bundle process when PR accepted.
- Publish on vic-ui builds bucket when PR accepted.
- Trigger downstream pipeline.
The develop branch could be used to e2e test bug fixes or hotfixes prior to being accepted on master branch.
It is a branch to eventually merge changes and e2e testing before going against master branch.

Add develop branch to trigger the downstream pipeline

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/mocks/create-vch-wizard-mocked-data.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.component.ts
h5c/vic/src/vic-webapp/src/app/interfaces/api-responses.ts
h5c/vic/src/vic-webapp/src/app/shared/constants/nodetype.ts
h5c/vic/src/vic-webapp/src/app/shared/utils/object-reference.ts
h5c/vic/src/vic-webapp/src/environments/global-properties.ts

This change will fix the endpoint to fetch the hosts of a VDS during VCH Creation Wizard in the Networ step. The new endpoint will be /ui/vic/rest/data/properties and it will be handled by our own vic java service layer.
Fixes #504 

Fix the endpoint to fetch the hosts of a VDS

---

scripts/VCSA/install.sh

This changes fix the bug installing vic plugin and coincidentally the Content Length has `404` pattern in it.
The case that trigger this failure was: 
`'Date: Wed, 20 Jun 2018 16:25:24 GMT08:08 GMT-- 0 HTTP/1.1 200 OK Time Time Time Current Dload Upload Total Spent Left Speed
++ echo % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed $'\r' 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- $'0\r' 0 6330k 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 HTTP/1.1 200 $'OK\r' Accept-Ranges: $'bytes\r' Content-Length: $'6482404\r' Content-Type: $'application/zip\r' Last-Modified: Tue, 19 Jun 2018 22:08:08 $'GMT\r' Date: Wed, 20 Jun 2018 16:25:24 $'GMT\r' $'\r'`
in which `Content-Length: $'6482404\r` has **404** pattern 
and validate incorrecltly the condition: …

Fix bug installing VIC plugin

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/registry-access/registry-access.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/registry-access/registry-access.component.ts

*   Fixed insecure registry with missing port not shown on the summary
*   Fix only show the colon after the ip if there is a port number
*   Add unit tests to validate insecure registries without port and without ip
*    Deleting console logs outputs
(cherry picked from commit e8e3267)

Cherry-pick: Fixed insecure registry with missing port not shown on summary (#467)

---

.drone.yml

The `master` branch of vic consumes the latest build from the `master` branch of vic-ui. Therefore it makes sense to trigger a build of `master` for each `push` to `master`.
The `release/*` branches of vic only consume `tag` builds of vic-ui. Therefore it makes sense to only trigger new builds of vic's release branches when performing a `tag` build of vic.
Eventually, we will be able to supply a specific build to be used by the downstream branch (see vmware/vic#6554). At that point, it will make sense to trigger downstream jobs as a result of `push` events to `develop` and `pull_request` events on all branches.
Related: vmware/vic#8057, vmware/vic#8058
---
[n/a] All unit tests pass
[n/a] All e2e tests pass
[n/a] Unit test(s) included*
[n/a] e2e test(s) included* …

Update drone config to specify downstream branch

---

tests/test-cases/Group18-VIC-UI/kickoff-tests.robot
tests/test-cases/Group18-VIC-UI/setup-testbed.robot
tests/test-cases/Group18-VIC-UI/vicui-common.robot

**Summary of changes:**
- Increase the poll time and retry time to get the response of the ssh service of the vcenter to prevent ssh connection timeouts.
- Stablish the minimum compatible esxi host version at the moment of the dvs creation (if we leave it blank it by default takes the exsi version as minimum dvs product compatible version, if we are deploying a 6.7 version, then 6.7 would be the minimum version and there is a big backward compatibility issue with already 6.5.0, 6.0.0 or 5.5.0 deployed versions, and those < 6.7.0 version can't be used, causing a failure on the e2e script, this happened when we did sanity checks against 6.7 version) .
- Read Jenkins jobs local variables for the vcenter build version and exsi version instead of the hardcoded ones.
Fixes #550 
PR acceptance …

Use parameterized vcenter and exsi version on setup-testbed robot file instead of hardcoded ones

---

scripts/VCSA/install.sh
scripts/VCSA/uninstall.sh
scripts/VCSA/upgrade.sh

Update the logic in `install.sh`, `upgrade.sh`, and `uninstall.sh` to use double quotes with variables and follow other Bash best practices to avoid word splitting, globbing, and some unnecessary use of subshells.
Additional cleanup to these scripts to reduce duplication, further reduce use of subshells, and avoid masking return values is possible, but is not included in this change to limit scope and risk.
---
Fixes #526

Revise lifecycle scripts to avoid word splitting

---

h5c/vic/src/vic-webapp/src/app/app.module.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-resource-treenode.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-resource-treenode.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-resource-treenode.template.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.module.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/mocks/create-vch-wizard-mocked-data.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/security/security.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/storage-capacity/storage-capacity.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/summary/summary.html
h5c/vic/src/vic-webapp/src/app/interfaces/api-responses.ts
h5c/vic/src/vic-webapp/src/app/interfaces/compute.resource.ts
h5c/vic/src/vic-webapp/src/app/shared/constants/nodetype.ts
h5c/vic/src/vic-webapp/src/app/shared/utils/object-reference.spec.ts
h5c/vic/src/vic-webapp/src/app/shared/utils/object-reference.ts
h5c/vic/src/vic-webapp/src/app/vch-view/vch.model.ts

This change will introduce a new logic into the resource tree selector component in order to allow users to be able to select Clusters within folders and also non-vic ResourcePools
NOTE: This is still pending to be manually tested and merged till API changes are fixed and merged into master: vmware/vic#6711
Fixes #468
[ n/a ] All e2e tests pass

Resource tree selector refactor

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/security/security.html

Contrary to what we [require](https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/vch_cert_options.html#server-key), the text previously stated that an "encrypted key pem file" should be selected. Correct this to indicate that an unencrypted file must be used.
Fixes #338

Specify that server key file must be unencrypted

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/security/security.html

Contrary to what we require[1], the text previously stated that an
"encrypted key pem file" should be selected. Correct this to indicate
that an unencrypted file must be used.
1 - https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/vch_cert_options.html#server-key
(cherry picked from commit 8c2b2043aa0bf5964a32f58bf9656be6bbce22c4)
---

Cherry-pick: Specify that server key file must be unencrypted (#575)

---

h5c/vic/src/vic-webapp/src/app/app.module.ts

This will add a missing service provider VicVmViewService that should be added to the root app Module in order to fix VIC summary view plugin.
Fixes #578 
[ n/a ] All e2e tests pass

Fix missed service provider VicVmViewService in the app module

---

.drone.yml

Builds from all branches are written to the same directory,
so it is difficult to select the right build from corresponding
branches for downstream projects. Publish builds from
release branches to the same name sub-directories in the
bucket.
Fixes #

Publish artifacts from release branches separately

---

.drone.yml

Builds from all branches are written to the same directory,
so it is difficult to select the right build from corresponding
branches for downstream projects. Publish builds from
release branches to the same name sub-directories in the
bucket.
(cherry picked from commit 026d0f9bb412dbbaba8125af88d24b7a4dfe64c6)
Fixes #

Cherry-pick: Publish artifacts from release branches separately (#582)

---

scripts/VCSA/install.sh
scripts/VCSA/uninstall.sh
scripts/VCSA/upgrade.sh

Update the logic in install.sh, upgrade.sh, and uninstall.sh to use
double quotes with variables and follow other Bash best practices to
avoid word splitting, globbing, and some unnecessary use of subshells.
Additional cleanup to these scripts to reduce duplication, further
reduce use of subshells, and avoid masking return values is possible,
but is not included in this change to limit scope and risk.
(cherry picked from commit 457fc5d60209c5fa53931adfcedcbba21a8d92b9)

Cherry-pick: Revise lifecycle scripts to avoid word splitting (#558)

---

.drone.yml

Enable make vic-ui-plugins in any conditions include tag.
Trigger downstream repo vic-product to make build for
tag event.
Fixes #

Enable tag event to make build

---

.drone.yml

Enable make vic-ui-plugins in any conditions include tag.
Trigger downstream repo vic-product to make build for
tag event.
(cherry picked from commit 7dfa7a25d218fd8a9243042aa970522346a21750)
Fixes #

Cherry-Pick: Enable tag event to make build (#591)

---

.drone.yml
Makefile

Git for-each-ref returns wrong tag name, use git describe to
get latest tag.
Remove branch and event conditions since branch is empty if
it is a tag event. Execute vic-ui and bundle when status is
success.
Fixes #

Fix errors when tag a build

---

.drone.yml
Makefile

Git for-each-ref returns wrong tag name, use git describe to
get latest tag.
Remove branch and event conditions since branch is empty if
it is a tag event. Execute vic-ui and bundle when status is
success.
(cherry picked from commit 586ed3f14d95bdd302baebcfd8911c56ecfe0b3a)
Fixes #

Cherry-Pick: Fix errors when tag a build (#593)

---

.drone.yml

Adding tag from git command is different from tagging from
github web, the branch is refs/tags/* instead of releases/*
. Add refs/tags/* to branch so tag from git command can
also publish builds and trigger downstream project.
Fixes #

Fix missing branch for tag event

---

.drone.yml

Adding tag from git command is different from tagging from
github web, the branch is refs/tags/* instead of releases/*
. Add refs/tags/* to branch so tag from git command can
also publish builds and trigger downstream project.
(cherry picked from commit c36a2f85b73f4bca1529ec18d3fbbfd787d76158)
Fixes #

Cherry-Pick: Fix missing branch for tag event (#597)

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts
h5c/vic/src/vic-webapp/src/app/summary-view/summary-view.component.html
h5c/vic/src/vic-webapp/src/app/summary-view/summary-view.component.spec.ts
h5c/vic/src/vic-webapp/src/app/summary-view/summary-view.component.ts
h5c/vic/src/vic-webapp/src/app/summary-view/vic-summary-view.scss

As the user is not able to select which API server to use (#572), providing this information may greatly aid debugging when multiple versions of API servers are available.
Fix:
1 Add vic appliance version information in summary view. 
2 Add vic appliance ip address in summary view.

Add vic appliance ip information in vic plugin summary view. 

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts
h5c/vic/src/vic-webapp/src/app/summary-view/summary-view.component.html
h5c/vic/src/vic-webapp/src/app/summary-view/summary-view.component.spec.ts
h5c/vic/src/vic-webapp/src/app/summary-view/summary-view.component.ts
h5c/vic/src/vic-webapp/src/app/summary-view/vic-summary-view.scss

As the user is not able to select which API server to use (#572), providing this information may greatly aid debugging when multiple versions of API servers are available.
Fix:
1 Add vic appliance version information in summary view.
2 Add vic appliance ip address in summary view.

add vic appliance ip information in summary view

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.html
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.scss

fix ip VIC plugin throws a parsing error when customer tries to specify only the gateway for management network.
When you provide a gateway for the management network, it's mandatory to provide at least one routing destination. UI Plugin doesn't reflect that. It has two separate fields for Gateway and Routing destinations. If the customer doesn't provide both the fields properly, plugin throws a weird parsing error [Refer to the screenshot].
Fix:
1 Modify UI to make routing destination required.
2 Modify the components destination input and ip address to one input.
Signed-off-by: Meina Zhou <meinaz@vmware.com>
Signed-off-by: Meina Zhou <meinaz@vmware.com>
(cherry picked from commit 38172238a4b1df4f3b30c608fc5abf771e85ec60)

Cherry-pick: bind gateway and routing destination input field together in ui (#583)

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts

If datacenter only contains host without cluster, host can not show in VCH create wizard. 
That is because a javascript error. 
Need to deal with the case datacenter does not contain cluster.

fix datacenter can not show host

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.component.ts

Issue description:
Currently, vic ui use: **--compute-resource $resourceId --compute-resource-name $resourceName** in the summary command line. 
Modify it as: 
**--compute-resource $resourceName**  instead.

use compute-resource in command string

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-capacity.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/compute-capacity/compute-resource-treenode.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts
h5c/vic/src/vic-webapp/src/app/shared/utils/array-utils.ts

in create vch wizard. In select "compute resource" view. 
The vcenter and clusters and hosts are not in correct order. That is because we get the data directly from vsphere sdk without sort them. 
fix:
In the ui view, add sort function to all those list to keep align with vcenter tree view.

fix cluster and vcenter order

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.html

Modify the container-network-gateway use CIDR format checking:
<input class="form-control" id="container-network-gateway" type="text" placeholder="IP address" formControlName="containerNetworkGateway">
+              <input class="form-control" id="container-network-gateway" type="text" placeholder="CIDR" formControlName="containerNetworkGateway">
and in the component.ts:
containerNetworkGateway: [{ value: '', disabled: true }, [
Validators.required,
-        Validators.pattern(ipPattern)
+        Validators.pattern(cidrPattern)
]],

container network gateway use cidr pattern

---

Makefile

VC only alllows 'major.minor.micro.build' format with digit number.
we should remove the rc# or dev tag for building vic-ui packages.

Cherry-pick: Removing the "-dev" tag in the vic-ui package path. (#621)

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts

Signed-off-by: Meina Zhou <meinaz@vmware.com>
in nsxt network if does not have dswitch,the promise should resolve a empty list, otherwise the promise does not resolved, so the network spinning will never stop.

fix network can not show up without dswitch

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.html

issue description: Before the regitry help document is link to https://vmware.github.io/vic-product/assets/files/html/1.5/vic_vsphere_admin/vch_security.html. It should open https://vmware.github.io/vic-product/assets/files/html/1.5/vic_vsphere_admin/vch_registry.html.

modify registry doc url

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/operations-user/operations-user.component.ts

fixed #2269
When creating VCH in vSphere client, at the last step, vSphere client user credential was needed, if blank space was attached by accident, there will be a failure of creating VCH.Therefore, use trim to remove spaces when getting the username entered.
Signed-off-by: FangyuanCheng <fangyuanc@vmware.com>

Enter required vSphere username to ignore spaces when deploying vch by GUI

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.html

Modify the network link according to documentation required. 
change the VIEW NETWORK REQUIREMENTS button to point to the new page, https://vmware.github.io/vic-product/assets/files/html/1.5/vic_vsphere_admin/network_reqs.html? The general help button at the top can stay as it is.

modify network links according to document

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/security/security.html

when upgrade clarity to 0.12. The alert component should use component style instead. Otherwise, need to inject a iconServiceProvider. This will cause all the alert message can not show up.

fix the clarity exception for security

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts

Fixes #220 
When using the plugin UI wizard to assign static IP to the management and client interfaces
The creation fails with this error:
> parsing vch body from "" failed, because json: cannot unmarshal object into Go struct field Network.static of type models.CIDR
The cause of this failure is in the way the UI constructs the request body. The static setting must be a string, not an object，so change the object of request body to a string
Signed-off-by: FangyuanCheng <fangyuanc@vmware.com>

Fix management and client interfaces static IP assignments

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.component.ts

The gateway is optional when using the plugin UI wizard to assign static IP to the client interface.
Signed-off-by: FangyuanCheng <fangyuanc@vmware.com>
Fixes #

Change the gateway in the client network to optional on ui

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.component.spec.ts
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.component.ts

When the gateway is empty, the gateway object will not be transmitted when the request is sent.
Signed-off-by: Fangyuan Cheng fangyuanc@vmware.com
Fixes #

Fix cannot assigne Static IP to Management and Client interface using Plugin UI Wizard

---

h5c/vic/src/vic-webapp/src/app/shared/utils/certificates.ts

the frontend will throw exception if user try to upload a pkcs1 format rsa private key. This fix will help to   allow user to upload pkcs1 format private key.

support pkcs1 format private key in ui wizard

---

h5c/vic-service/src/main/resources/META-INF/MANIFEST.MF
h5c/vic/src/main/webapp/META-INF/MANIFEST.MF

in vc 6.7 u2, many lib package upgraded, that lead to we need to modify MANIFEST files  to remove the version control to let vc load new packages after upgrade.

fix vic plugin can not show in vc6.7u2

---

h5c/vic-service/src/main/java/com/vmware/vic/PropFetcher.java

In sumarry and vch page. Many apis are invoked concurrently to get the container and vch information
In our code 
private Root getRootObject() 
This api will get VCH and container information. They invoke the same method. and create container view to get exproperties from vc. We need to add synchronized key in the  ResultItem getVicVms(boolean isVch)  in PropFetcher.java

fix link mode can not get appliance error

---

h5c/vic-service/src/main/java/com/vmware/vic/PropFetcher.java

fix link mode create vch and delete vch will have 400 wrong user name and password error. create clone ticket need to use synchronised keyword to the invoke function. vc will not close the session. We need to investigate why will happen this. This will be the future work

Fix linkmode create vch and delete vch will report wrong password and user name error

---

h5c/vic/src/vic-webapp/src/app/shared/utils/certificates.ts

Some of the windows user which use openssl generated certificate has different line ending with linux. 
For linux the line ending will use: /n
For windows the line ending will use: /r/n. 
therefore, we need to also handle windows scenario to support filter out the beginning string and end string.

fix issue for window certificate has /r charactor in file

---

h5c/vic-service/src/main/java/com/vmware/vic/PropFetcher.java
h5c/vic/src/vic-webapp/src/app/summary-view/summary-view.component.html

change the get appliance api return fqdn instead of ip address to avoid some users can not access the ip address , because certificate only work for fqdn access. 
Therefore to keep consistency, frontend also changed the summary page to show fqdn instead of ip.

change the ip address of appliance to fqdn

---

h5c/vic-service/src/main/java/com/vmware/utils/ssl/ThumbprintHostNameVerifier.java
h5c/vic-service/src/main/java/com/vmware/utils/ssl/ThumbprintTrustManager.java

In certificate chain environment. Java ssl trustManager will get multiple certs in the backend. 
The old logic will suppose each certs will be in the vcenter server info thumbprint sets. Actually, in this case only one cert thumbprint will in the thumbprint sets. So this logic need to be updated. Modify the logic to suppose vcenter sets will match any of the cert thumbprint from session. If none of the cert thumbprint match the vcenter thumbprint , then throw the exception.

fix certificate chain will not show vic plugin

---

h5c/vic-service/src/main/java/com/vmware/vic/PropFetcher.java
h5c/vic-service/src/main/java/com/vmware/vic/cache/LocalCache.java

It will be serious performance problem when have large scale of vms. That because the propFetcher will invoke getVicVms for more than 10 times. This method will be very slow if large scale of vms. 
This pr is focus on introduce a memory cache and set the timeout to no more than 1 min to avoid interact with vc vim 25 interface.

add timeout cache for getVicVms

---

h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.scss
h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts

Signed-off-by: Meina Zhou <meinaz@vmware.com>
Fix the layout in create vch in vsphere 6.7 u3. Because the modal dialog has some changes. The original element no longer exist. Need to modify to compatible way. 
Fixes #

fix layout issue in vc u3

---

h5c/vic/src/vic-webapp/package-lock.json
h5c/vic/src/vic-webapp/package.json

At present, only part of it can be upgraded. If it is completely upgraded, only angular.
Signed-off-by: Yogi_Wang <yawang@vmware.com>
Fixes #

[upgrade] (dependencies ui) Upgrade part of ui packages when it has vulnerbilities

---

h5c/vic-service/src/main/java/com/vmware/vic/PropFetcher.java

Current VIC UI plugin can not be shown up on vsphere-client7.0.2 due to new security requirements.
For fix this issue, we need to change protocol from 'SSL' to 'TLS'.
Fixes #696
[] Unit test(s) included*
[n/a ] e2e test(s) included*
[n/a] Screenshot attached and UX approved*

Support vic ui plugin running on vc 7.0.2
